*;
*MOST FREQUENT VALUE (COUNT);
*;
length IMP_JOB $7;
label IMP_JOB = 'Imputed JOB';
IMP_JOB = JOB;
if JOB = '' then IMP_JOB = 'Other';
length IMP_REASON $7;
label IMP_REASON = 'Imputed REASON';
IMP_REASON = REASON;
if REASON = '' then IMP_REASON = 'DebtCon';
*;
*MEAN-MAX-MIN-MEDIAN-MIDRANGE AND ROBUST ESTIMATES;
*;
label IMP_CLAGE = 'Imputed CLAGE';
IMP_CLAGE = CLAGE;
if missing(CLAGE) then IMP_CLAGE = 182.51421356;
label IMP_CLNO = 'Imputed CLNO';
IMP_CLNO = CLNO;
if missing(CLNO) then IMP_CLNO = 21.216440752;
label IMP_DEBTINC = 'Imputed DEBTINC';
IMP_DEBTINC = DEBTINC;
if missing(DEBTINC) then IMP_DEBTINC = 33.907492422;
label IMP_DELINQ = 'Imputed DELINQ';
IMP_DELINQ = DELINQ;
if missing(DELINQ) then IMP_DELINQ = 0.4679069767;
label IMP_DEROG = 'Imputed DEROG';
IMP_DEROG = DEROG;
if missing(DEROG) then IMP_DEROG = 0.2433460076;
label IMP_MORTDUE = 'Imputed MORTDUE';
IMP_MORTDUE = MORTDUE;
if missing(MORTDUE) then IMP_MORTDUE = 73215.742741;
label IMP_NINQ = 'Imputed NINQ';
IMP_NINQ = NINQ;
if missing(NINQ) then IMP_NINQ = 1.1503208066;
label IMP_VALUE = 'Imputed VALUE';
IMP_VALUE = VALUE;
if missing(VALUE) then IMP_VALUE = 102461.00508;
label IMP_YOJ = 'Imputed YOJ';
IMP_YOJ = YOJ;
if missing(YOJ) then IMP_YOJ = 8.8810123683;
*;
*INDICATOR VARIABLES;
*;
label M_CLAGE = "Imputation Indicator for CLAGE";
if missing(CLAGE) then M_CLAGE = 1;
else M_CLAGE= 0;
label M_CLNO = "Imputation Indicator for CLNO";
if missing(CLNO) then M_CLNO = 1;
else M_CLNO= 0;
label M_DEBTINC = "Imputation Indicator for DEBTINC";
if missing(DEBTINC) then M_DEBTINC = 1;
else M_DEBTINC= 0;
label M_DELINQ = "Imputation Indicator for DELINQ";
if missing(DELINQ) then M_DELINQ = 1;
else M_DELINQ= 0;
label M_DEROG = "Imputation Indicator for DEROG";
if missing(DEROG) then M_DEROG = 1;
else M_DEROG= 0;
label M_JOB = "Imputation Indicator for JOB";
if JOB = '' then M_JOB = 1;
else M_JOB= 0;
label M_MORTDUE = "Imputation Indicator for MORTDUE";
if missing(MORTDUE) then M_MORTDUE = 1;
else M_MORTDUE= 0;
label M_NINQ = "Imputation Indicator for NINQ";
if missing(NINQ) then M_NINQ = 1;
else M_NINQ= 0;
label M_REASON = "Imputation Indicator for REASON";
if REASON = '' then M_REASON = 1;
else M_REASON= 0;
label M_VALUE = "Imputation Indicator for VALUE";
if missing(VALUE) then M_VALUE = 1;
else M_VALUE= 0;
label M_YOJ = "Imputation Indicator for YOJ";
if missing(YOJ) then M_YOJ = 1;
else M_YOJ= 0;
