*------------------------------------------------------------*;
* TRANSFORM: CLAGE , log(CLAGE + 1);
*------------------------------------------------------------*;
label LOG_CLAGE = 'Transformed CLAGE';
if CLAGE eq . then LOG_CLAGE = .;
else do;
if CLAGE + 1 > 0 then LOG_CLAGE = log(CLAGE + 1);
else LOG_CLAGE = .;
end;
*------------------------------------------------------------*;
* TRANSFORM: CLNO , log(CLNO + 1);
*------------------------------------------------------------*;
label LOG_CLNO = 'Transformed CLNO';
if CLNO eq . then LOG_CLNO = .;
else do;
if CLNO + 1 > 0 then LOG_CLNO = log(CLNO + 1);
else LOG_CLNO = .;
end;
*------------------------------------------------------------*;
* TRANSFORM: DEBTINC , log(DEBTINC + 1);
*------------------------------------------------------------*;
label LOG_DEBTINC = 'Transformed DEBTINC';
if DEBTINC eq . then LOG_DEBTINC = .;
else do;
if DEBTINC + 1 > 0 then LOG_DEBTINC = log(DEBTINC + 1);
else LOG_DEBTINC = .;
end;
*------------------------------------------------------------*;
* TRANSFORM: DELINQ , log(DELINQ + 1);
*------------------------------------------------------------*;
label LOG_DELINQ = 'Transformed DELINQ';
if DELINQ eq . then LOG_DELINQ = .;
else do;
if DELINQ + 1 > 0 then LOG_DELINQ = log(DELINQ + 1);
else LOG_DELINQ = .;
end;
*------------------------------------------------------------*;
* TRANSFORM: DEROG , log(DEROG + 1);
*------------------------------------------------------------*;
label LOG_DEROG = 'Transformed DEROG';
if DEROG eq . then LOG_DEROG = .;
else do;
if DEROG + 1 > 0 then LOG_DEROG = log(DEROG + 1);
else LOG_DEROG = .;
end;
*------------------------------------------------------------*;
* TRANSFORM: LOAN , log(LOAN + 1);
*------------------------------------------------------------*;
label LOG_LOAN = 'Transformed LOAN';
if LOAN eq . then LOG_LOAN = .;
else do;
if LOAN + 1 > 0 then LOG_LOAN = log(LOAN + 1);
else LOG_LOAN = .;
end;
*------------------------------------------------------------*;
* TRANSFORM: MORTDUE , log(MORTDUE + 1);
*------------------------------------------------------------*;
label LOG_MORTDUE = 'Transformed MORTDUE';
if MORTDUE eq . then LOG_MORTDUE = .;
else do;
if MORTDUE + 1 > 0 then LOG_MORTDUE = log(MORTDUE + 1);
else LOG_MORTDUE = .;
end;
*------------------------------------------------------------*;
* TRANSFORM: VALUE , log(VALUE + 1);
*------------------------------------------------------------*;
label LOG_VALUE = 'Transformed VALUE';
if VALUE eq . then LOG_VALUE = .;
else do;
if VALUE + 1 > 0 then LOG_VALUE = log(VALUE + 1);
else LOG_VALUE = .;
end;
*------------------------------------------------------------*;
* TRANSFORM: YOJ , log(YOJ + 1);
*------------------------------------------------------------*;
label LOG_YOJ = 'Transformed YOJ';
if YOJ eq . then LOG_YOJ = .;
else do;
if YOJ + 1 > 0 then LOG_YOJ = log(YOJ + 1);
else LOG_YOJ = .;
end;
